### ISSUE TITLE
Could you update this datasource plugin to grafanan 4.x ?

### ISSUE THREAD

**Issue by zhengguangpeng** [briangann/grafana3-atlas-datasource#2]
grafana has published new version of 4.* (4.6.2 at now) ,could you update this plugin according to the latest verion ?

thank you.

**Comment by briangann** [comment]
It does actually work with Grafana 4.x.  It really just needs to be renamed and submitted to the grafana.com as a datasource.

**Comment by zhengguangpeng** [comment]
But when I apply this plugin into Grafana  4.5.2, when I selected one metrics ,no data could be displayed and the "loading" image is on...

But with grafana 3.1.1 ,it's okey.


![image](https://user-images.githubusercontent.com/5219174/33304992-ea54b98a-d446-11e7-904d-c0529bccdcc3.png)

**Comment by zhengguangpeng** [comment]
![image](https://user-images.githubusercontent.com/5219174/33305106-74a1f792-d447-11e7-91d0-daa245e55a13.png)

error with js ...

**Comment by zhengguangpeng** [comment]
sorry , I check datasource.js again ,your version has changed , maybe there's something wrong when I configed the environment .

I'll check it again.

**Comment by zhengguangpeng** [comment]
Sorry , I check again the version and find the problem .  At first ,I download the version "20161124*" and now I chang to the "master" version .

I did not know about the difference between the two versions.

Thank you.
